-- Supabase / PostgreSQL seed script for the POS app.
-- Run this in the Supabase SQL Editor or any PostgreSQL client.

DROP TABLE IF EXISTS transaction_details CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE branches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  address varchar(255) NOT NULL
);

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  role_id integer NOT NULL REFERENCES roles(id),
  branch_id integer NOT NULL REFERENCES branches(id)
);

CREATE TABLE categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL,
  price numeric(12,2) NOT NULL,
  stock integer NOT NULL DEFAULT 0,
  category_id integer NOT NULL REFERENCES categories(id),
  branch_id integer NOT NULL REFERENCES branches(id)
);

CREATE TABLE transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number varchar(50) NOT NULL UNIQUE,
  user_id integer NOT NULL REFERENCES users(id),
  branch_id integer NOT NULL REFERENCES branches(id),
  total numeric(12,2) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE transaction_details (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id integer NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id),
  qty integer NOT NULL,
  price numeric(12,2) NOT NULL,
  subtotal numeric(12,2) NOT NULL
);

INSERT INTO roles (name) VALUES
('admin'),
('cashier');

INSERT INTO branches (name, address) VALUES
('Cabang Jakarta', 'Jl. Melati No. 1, Jakarta'),
('Cabang Bandung', 'Jl. Braga No. 7, Bandung'),
('Cabang Surabaya', 'Jl. Rajawali No. 10, Surabaya');

INSERT INTO categories (name) VALUES
('Minuman'),
('Makanan'),
('Snack');

INSERT INTO users (username, password, role_id, branch_id) VALUES
('admin', '$2b$10$3WeiTyktmesma7FRw.yFf.FgmpUAY1DuitKoJ.Asj4RS1dJnHH4vq', 1, 1),
('kasir01', '$2b$10$nDww0oCr3PZEC2jKdpQIsunAPxIsI9twSzVrBu/CNTHs7XKhFui4q', 2, 2),
('adminops', '$2b$10$Co1lMaKsatmI2LtGGH7X0e2DFtu.oAHNbwVHiikPM.WZ3V5tSVZea', 1, 1),
('adminbdg', '$2b$10$5DjGoAWUTAehVpFrKfPgKe9qp1uztcqzJSlWN/Ui66Vjz6rEvqUCu', 1, 2),
('kasirjkt', '$2b$10$nh8OLuMKoHgRbM9om1g/Rej6e.y0p6AN5NrPQR9LxqS1iBxXF375W', 2, 1),
('kasirsby', '$2b$10$d9b5Co3/norE9xbIpqEP1OHOGeq6zyISHFhGpCReLTDqKiIoci30i', 2, 3);

INSERT INTO products (name, price, stock, category_id, branch_id) VALUES
('Americano', 18000.00, 45, 1, 1),
('Latte', 24000.00, 32, 1, 1),
('Croissant', 22000.00, 18, 2, 1),
('Mie Goreng', 28000.00, 24, 2, 2),
('Es Teh Lemon', 14000.00, 50, 1, 2),
('Keripik Kentang', 12000.00, 16, 3, 3);

INSERT INTO transactions (invoice_number, user_id, branch_id, total, created_at) VALUES
('INV-20260407-001', 2, 2, 56000.00, '2026-04-07 10:40:00+00'),
('INV-20260407-002', 1, 1, 58000.00, '2026-04-07 11:10:00+00');

INSERT INTO transaction_details (transaction_id, product_id, qty, price, subtotal) VALUES
(1, 4, 2, 28000.00, 56000.00),
(2, 1, 2, 18000.00, 36000.00),
(2, 3, 1, 22000.00, 22000.00);
